# Generated by Django 6.0.5 on 2026-06-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='asaas_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('FALHADO', 'Falhado')], default='PENDENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='contato',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='profissao',
            field=models.CharField(max_length=100),
        ),
    ]
