name: Django CI/CD Pipeline

# O pipeline será acionado toda vez que houver um 'push' ou 'pull request' na branch principal (main)
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # 1. STEP DE LINT E TESTES
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v3

    - name: Configurar o Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Instalar o Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Instalar Dependências do Projeto
      run: poetry install

    # O Lint verifica se o código segue as boas práticas visuais do Python (PEP 8)
    - name: Run Lint (Verificação de estilo)
      run: |
        poetry add flake8 --dev
        poetry run flake8 .

    # Executa os mesmos testes que acabou de rodar localmente
    - name: Run Tests (Testes Automatizados)
      run: |
        poetry run python manage.py test

  # 2. STEP DE BUILD (Empacotamento com Docker)
  build:
    needs: lint-and-test # Só roda se os testes passarem
    runs-on: ubuntu-latest
    steps:
    - name: Baixar o código
      uses: actions/checkout@v3

    - name: Simular Build da Imagem Docker
      run: |
        docker build -t lacrei-saude-api:latest .

  # 3. STEP DE DEPLOY (Placeholders para o ambiente AWS)
  deploy:
    needs: build # Só roda se o build der certo
    runs-on: ubuntu-latest
    steps:
    - name: Deploy para Staging/Produção (AWS)
      run: |
        echo "Conectando na AWS..."
        echo "Executando estratégia de Rollback / Blue-Green Deployment..."
        echo "API Lacrei Saúde atualizada com sucesso!"